### ISSUE TITLE
Unhandled exception when saving file

### ISSUE THREAD

**Issue by DarkMatterMatt** [benchen71/epub-metadata-editor#32]
```
************** Exception Text **************
System.ArgumentException: Argument 'Start' must be greater than zero.
   at Microsoft.VisualBasic.Strings.InStr(Int32 Start, String String1, String String2, CompareMethod Compare)
   at EPubMetadataEditor.Form1.CleanOPF(String metadatafile)
   at EPubMetadataEditor.Form1.SaveEpub(String EpubFileName, Boolean SaveOPFOnly)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

This is the book causing the issue: ![the subtle knife - philip pullman epub](https://user-images.githubusercontent.com/15150339/35178809-21758b80-fdf3-11e7-8a1e-eb7414efd347.jpg)

I have a few books which this happens with, I've noticed that they all have terrible metadata and are _missing titles_ and there is a _date in the series index_ field, don't ask me why 😛 It's probably unrelated.

**Comment by benchen71** [comment]
Hi DarkMatterMatt,

I'm afraid the metadata of this epub is badly formed.  I don't think I can modify my program to handle this sort of error.  However, you can do this manually using my program.  You will have to edit the opf file, and there is a button for this in the Advanced Tasks panel.

Here are the first two lines of the opf:

```
<?xml vers    <dc:format>ePub</dc:format>
    <dc:subject>Fantasy:General</dc:subject>
```

As you can see, the opening xml item is not all there.  Something has deleted the rest of that xml item, the opening package item, the opening metadata item, and presumably a number of other lines containing the epub title and author information.  To fix this, you would need to replace

`<?xml vers`

with

```
<?xml version="1.0"  encoding="UTF-8"?>
<package xmlns="http://www.idpf.org/2007/opf" version="2.0">
    <metadata xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:opf="http://www.idpf.org/2007/opf">
```

My program can then be used to add the missing metadata.

(However, I can modify my program to better handle the error you are experiencing.)

**Comment by DarkMatterMatt** [comment]
I suspected that it was the metadata causing the issue. It would be helpful if your program said something like "malformed metadata" instead of that random error 😄 

Thanks, Matt

**Comment by benchen71** [comment]
Yes, the next version will provide a proper error message.
